### ISSUE TITLE
infinite looping / freeze

### ISSUE THREAD

**Issue by sebastiankr** [spencermountain/compromise#561] opened 2019-01-28 16:25 UTC
The following string 'crashes' nlp(). 
Background: This is from a table of contends in a scanned and OCR'ed document. 

"2   DETAILED FINDINGS AND RECOMMENDATIONS......................................................7"

It works, when there is a space between the dots and the page number.

awesome lib!

**Comment by spencermountain** [comment] 2019-01-28 19:54
you found it!
thanks Sebastian.
this is a dupe of #511 and is a gross regex i wrote, then couldn't figure-out how to fix.
I'll close this, but maybe I should hotfix 511.
There's a big rewrite of some of this stuff, it's a few weeks away though
cheers!

**Closed by spencermountain** 2019-01-28 19:54 UTC
